web:
  image: pdxjohnny/numapp
  command: /app/run http --cert=
  ports:
    - "12345:8080"
  volumes:
    - ./static:/app/static
  links:
    - db
  environment:
    SERVICE_PROTOCOL: "http"
db:
  image: pdxjohnny/numapp
  command: /app/run db --cert=
  expose:
    - "42345"
  links:
    - mongo
mongo:
  image: mongo
