web:
  image: pdxjohnny/numapp:dev
  command: /app/run http
  ports:
    - "12345:8080"
  volumes:
    - ./static:/app/static
  links:
    - user
    - db
  environment:
    NUMAPP_CERT: "false"
    SERVICE_PROTOCOL: "http"
user:
  image: pdxjohnny/numapp:dev
  command: /app/run user
  ports:
    - "32345"
  links:
    - db
  environment:
    NUMAPP_CERT: "false"
    SERVICE_PROTOCOL: "http"
db:
  image: pdxjohnny/numapp:dev
  command: /app/run db
  expose:
    - "42345"
  links:
    - mongo
  environment:
    NUMAPP_CERT: "false"
mongo:
  image: mongo
