web:
  image: bbbs/backend:dev
  command: /app/run http
  ports:
    - "12345:8080"
  volumes:
    - ./static:/app/static
  links:
    - user
    - db
  environment:
    BACKEND_CERT: "false"
    SERVICE_PROTOCOL: "http"
user:
  image: bbbs/backend:dev
  command: /app/run user
  expose:
    - "32345"
  links:
    - db
  environment:
    BACKEND_CERT: "false"
    SERVICE_PROTOCOL: "http"
db:
  image: bbbs/backend:dev
  command: /app/run db
  expose:
    - "42345"
  links:
    - mongo
  environment:
    BACKEND_CERT: "false"
mongo:
  image: mongo
  volumes:
    - /srv/docker/mongodb:/var/lib/mongodb
